"""empty message

Revision ID: 057bbb1290ce
Revises: ee0b68527a85
Create Date: 2024-10-16 15:54:42.356831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057bbb1290ce'
down_revision = 'ee0b68527a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('capcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
